version: '3'

services:
  backendservice:
    image: aelmo/rest-api-social-meli
    container_name: social-meli
    build:
      context: ../spring-challenge
      args:
        - PORT=8080
    ports:
      - "8080:8080"